Repository chat-loc/chatloc.github.io, pull requests merged in 2020-07, with the labels that each got.

#2 Add initial proposition
  README.md
Labels: good first issue

#5 Added project ideas for the collab app
  README.md
Labels: documentation

#6 added project startup ideas
  README.md
Labels: documentation

#8 Introduce starter files and registration module
  css/default.css
  css/home.css
  css/media-query.css
  css/reset.css
  css/reusable-class.css
  images/bg.jpg
  images/collaboratescene_1.png
  images/collaboratescene_2x.png
  images/hamburger.png
  index.html
  js/script.js
  login.html
Labels: enhancement

#14 Save users db
  controllers/Login.js
  controllers/User.js
  index.js
  models/Login.js
  models/User.js
  public/css/form.css
  public/css/index.css
  views/General/404.handlebars
  views/User/login.handlebars
  views/User/registration.handlebars
Labels: enhancement

#15 Update time-tracker
  config/handlebars-helpers.js
  time-tracker.xlsx
Labels: enhancement

#17 Control both login and registration model with one controller (User.js)
  controllers/Login.js
  controllers/User.js
  index.js
  public/css/form.css
  views/User/login.handlebars
  views/User/registration.handlebars
Labels: duplicate

#20 Implement authentication and session
  controllers/General.js
  controllers/User.js
  index.js
  models/Login.js
  models/User.js
  package-lock.json
  package.json
  public/css/index.css
  public/css/roomlist.css
  public/js/nav.js
  public/js/opencage.js
  public/js/script.js
  views/General/roomlist.handlebars
  views/User/login.handlebars
  views/User/registration.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#21 List rooms, generate logged in users from district and origin
  controllers/User.js
  public/css/index.css
  public/css/roomlist.css
  time-tracker.xlsx
  views/General/roomlist.handlebars
Labels: enhancement

#26 Chat Prototype
  .gitignore
  New folder/chat.html
  New folder/css/style.css
  New folder/images/down-arrow.png
  New folder/images/home.png
  New folder/images/magnifying-glass-pngrepo-com.png
  New folder/images/magnifying-glass-svgrepo-com.svg
  New folder/images/notification.png
  New folder/images/plus-button.png
  New folder/images/settings.png
  New folder/images/user-dummy-image.png
  New folder/images/user.png
  README.md
  config/handlebars-helpers.js
  controllers/Chat.js
  controllers/General.js
  controllers/User.js
  db.json
  index.js
  models/Chat.js
  models/Login.js
  models/User.js
  package-lock.json
  package.json
  public/css/chat.css
  public/css/font.css
  public/css/form.css
  public/css/index.css
  public/css/roomlist.css
  public/fonts/futura/Futura Bold font.ttf
  public/fonts/futura/Futura Book font.ttf
  public/fonts/futura/Futura Light font.ttf
  public/fonts/futura/futur.ttf
  public/fonts/futura/futura medium bt.ttf
  public/fonts/futura/unicode.futurab.ttf
  public/images/bg.jpg
  public/images/cloud.png
  public/images/collaboratescene_1.png
  public/images/collaboratescene_2x.png
  public/images/hamburger.png
  public/images/page-bg-2.jpg
  public/images/page-bg.png
  public/images/toronto-map.png
  public/js/connect.js
  public/js/index.js
  public/js/nav.js
  public/js/opencage.js
  public/js/script.js
  public/sounds/user-joins.mp3
  time-tracker.xlsx
  views/General/404.handlebars
  views/General/roomlist.handlebars
  views/User/etobicoke-north-room.handlebars
  views/User/login.handlebars
  views/User/registration.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#27 App Prototype
  New folder/chat.html
  New folder/css/style.css
  New folder/images/down-arrow.png
  New folder/images/home.png
  New folder/images/magnifying-glass-pngrepo-com.png
  New folder/images/magnifying-glass-svgrepo-com.svg
  New folder/images/notification.png
  New folder/images/plus-button.png
  New folder/images/settings.png
  New folder/images/user-dummy-image.png
  New folder/images/user.png
  README.md
  controllers/Chat.js
  controllers/General.js
  controllers/User.js
  db.json
  index.js
  models/Chat.js
  package-lock.json
  package.json
  public/css/chat.css
  public/css/index.css
  public/css/roomlist.css
  public/js/connect.js
  public/js/nav.js
  public/js/opencage.js
  public/sounds/user-joins.mp3
  views/General/roomlist.handlebars
  views/User/etobicoke-north-room.handlebars
  views/User/registration.handlebars
  views/layouts/main.handlebars
Labels: enhancement

#28 Chat-Loc Prototype
  time-tracker.xlsx
Labels: enhancement

#33 Chat loc 1.0
  README.md
  controllers/User.js
  index.js
  public/css/chat.css
  public/css/index.css
  public/css/roomlist.css
  public/images/ico.chit-chat-loc.ico
  public/js/connect.js
  public/js/nav.js
  views/General/roomlist.handlebars
  views/User/chatroom.handlebars
  views/User/etobicoke-north-room.handlebars
  views/User/india-room.handlebars
  views/User/nigeria-room.handlebars
  views/layouts/main.handlebars
Labels: enhancement
